[workspace]
members = ["crates/slk-state-cli", "crates/slk-state-core"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
version = "4.0.0"

[workspace.dependencies]
directories = "6.0.0"
rusqlite = { version = "0.37.0", features = ["backup", "bundled"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.10.9"
thiserror = "2.0.19"
uuid = { version = "1.24.0", features = ["v4"] }
